### ISSUE TITLE
the cost of regularization in Network2.py total_cost should not in the loop?

### ISSUE THREAD

**Issue by llgithubll** [MichalDanielDobrzanski/DeepLearningPython35#12]
```
def total_cost(self, data, lmbda, convert=False):
        cost = 0.0
        for x, y in data:
            a = self.feedforward(x)
            if convert: y = vectorized_result(y)
            cost += self.cost.fn(a, y)/len(data)
            cost += 0.5*(lmbda/len(data))*sum(np.linalg.norm(w)**2 for w in self.weights) # '**' - to the power of.
        return cost
```

the cost of regularization should not in the loop?

**Comment by MichalDanielDobrzanski** [comment]
https://github.com/mnielsen/neural-networks-and-deep-learning/blob/86b38f5ba4d402b60167a82d638616f5e16f2f51/src/network2.py

http://neuralnetworksanddeeplearning.com/chap3.html#overfitting_and_regularization - please take a look at equation **85**

Yes, it should not be in the loop, as you calculate total cost for all vectors (x and y respectively).
