### ISSUE TITLE
lmbda in update_mini_batch

### ISSUE THREAD

**Issue by NickYi1990** [MichalDanielDobrzanski/DeepLearningPython35#16]
self.weights = [(1-eta*(lmbda/n))*w-(eta/len(mini_batch))*nw for w, nw in zip(self.weights, nabla_w)]
why n is the training dataset size not the batch_size?

**Comment by wikty** [comment]
Please check the 87 and 92 equations in the [neuralnetworksanddeeplearning.com](http://neuralnetworksanddeeplearning.com/chap3.html#overfitting_and_regularization)

**Comment by MichalDanielDobrzanski** [comment]
Closing, since this is not an issue.
