### ISSUE TITLE
Missing sigmoid_prime()

### ISSUE THREAD

**Issue by DOUS3L** [MichalDanielDobrzanski/DeepLearningPython35#17]
https://github.com/MichalDanielDobrzanski/DeepLearningPython35/blob/ea229ac6234b7f3373f351f0b18616ca47edb8a1/network2.py#L253

here it should be
delta = self.cost_derivative(activations[-1], y) * sigmoid_prime(zs[-1]) 
the code from the book does that 
![image](https://user-images.githubusercontent.com/18417286/48530828-2ebe5c80-e8cc-11e8-8b17-ad2e3a2608cf.png)

**Comment by cgarbin** [comment]
@DOUS3L I'm using this code for a class exercise and came across your comment. Would you mind clarifying where you see the code in the book dividing by `sigmoid_prime(sz[-1])?

The code in chapter 2 does that. However, network2.py comes from [this section in chapter 3](http://neuralnetworksanddeeplearning.com/chap3.html#handwriting_recognition_revisited_the_code). 

The code looks like this:

        # backward pass
        delta = (self.cost).delta(zs[-1], activations[-1], y)
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())

**Comment by MichalDanielDobrzanski** [comment]
The cost can be defined in the main `test.py` script for running the network learning algorithm.
Hence, this is an basic implementation which should not assume to use the specific loss funciton.
