### ISSUE TITLE
Pandas, Numpy packages are not getting executed

### ISSUE THREAD

**Issue by prasadhebbar** [MichalDanielDobrzanski/DeepLearningPython35#31]
Hello,

I am running the following commands on Jupyter Notebook (Anaconda) and getting following error. Not able to proceed with programming.

import numpy as np

AttributeError                            Traceback (most recent call last)
<ipython-input-2-0aa0b027fcb6> in <module>
----> 1 import numpy as np

~\Anaconda3\lib\site-packages\numpy\__init__.py in <module>
    138     from . import _distributor_init
    139 
--> 140     from . import core
    141     from .core import *
    142     from . import compat

~\Anaconda3\lib\site-packages\numpy\core\__init__.py in <module>
     96 # do this after everything else, to minimize the chance of this misleadingly
     97 # appearing in an import-time traceback
---> 98 from . import _add_newdocs
     99 # add these for module-freeze analysis (like PyInstaller)
    100 from . import _dtype_ctypes

~\Anaconda3\lib\site-packages\numpy\core\_add_newdocs.py in <module>
   4402     allocating the array data. Returns the previously set value.
   4403     See `global_state` for more information.
-> 4404     """)
   4405 
   4406 add_newdoc('numpy.core._multiarray_tests', 'format_float_OSprintf_g',

~\Anaconda3\lib\site-packages\numpy\core\function_base.py in add_newdoc(place, obj, doc, warn_on_python)
    504     If possible it should be avoided.
    505     """
--> 506     new = getattr(__import__(place, globals(), {}, [obj]), obj)
    507     if isinstance(doc, str):
    508         _add_docstring(new, doc.strip(), warn_on_python)

AttributeError: module 'numpy.core.multiarray' has no attribute '_set_madvise_hugepage'

**Comment by MichalDanielDobrzanski** [comment]
Hey @prasadhebbar. Unfortunately, I have no idea how to set this up in Jupyter. I was only running this script from command line.

Probably you need to set proper numpy version on Jupyter desktop to make this run.

Since this out of scope, I am closing this issue.
