### ISSUE TITLE
ImportError: cannot import name 'downsample'

### ISSUE THREAD

**Issue by itosve** [MichalDanielDobrzanski/DeepLearningPython35#5]
Running Mac OS X Sierra High, Python 3.6, got the Error: 
ImportError: cannot import name 'downsample', when running python test.py

Solution:
Had to change the following lines to get it work:

#from theano.tensor.signal import downsample
from theano.tensor.signal import pool

#pooled_out = downsample.max_pool_2d(
pooled_out = pool.pool_2d( 

and also clear the theano cache: theano-cache purge

**Comment by MichalDanielDobrzanski** [comment]
Issue resolved with merge request:
https://github.com/MichalDanielDobrzanski/DeepLearningPython35/pull/2
